/** The bundle's stylesheet is Radix Themes' own, scoped to the Provider's wrapper (SPEC §9.2). */
import {readFileSync} from 'node:fs';
import {expect, test} from 'vitest';

// Generated by scripts/scope-radix.mjs before every build, test and dev run; path from the package root.
const css = readFileSync('src/radix-themes.scoped.css', 'utf8');

test('no declaration lands at :root — every one Radix made there now sits on the wrapper', () => {
  expect(css).not.toMatch(/:root/);
  expect(css).toMatch(/\.a2uiverse-shell-catalog\s*[,{]/);
});

test('the sheet is still Radix: tokens, components and the appearance classes are all there', () => {
  expect(css).toContain('--gray-1:');
  expect(css).toContain('.rt-SelectTrigger');
  expect(css).toMatch(/\.dark\b/);
});

test('every custom property the sheet reads is declared by the sheet — none is borrowed', () => {
  const declared = new Set([...css.matchAll(/(--[\w-]+)\s*:/g)].map(m => m[1]));
  const borrowed = [...new Set([...css.matchAll(/var\(\s*(--[\w-]+)/g)].map(m => m[1]))].filter(
    name => !declared.has(name),
  );
  expect(borrowed).toEqual([]);
  expect(css).toContain('--radix-select-trigger-width:initial');
});
