/**
 * The pinned A2UI spec schemas (`../a2ui-spec`, copied by `sync-a2ui-spec.mjs`) are shipped as
 * values the A2UI validator compiles — the sdk runs in the browser too, so it cannot read files.
 * This script embeds them into `src/a2ui/spec.generated.ts`; build, typecheck and test run it
 * first. Generated, never edited.
 */
import {mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const spec = resolve(here, '../../a2ui-spec');
const target = resolve(here, '../src/a2ui/spec.generated.ts');

const read = path => JSON.parse(readFileSync(resolve(spec, path), 'utf8'));
const upstream = read('UPSTREAM.json');
const serverToClient = read('specification/v0_9_1/json/server_to_client.json');
const commonTypes = read('specification/v0_9_1/json/common_types.json');
const serverCapabilities = read('specification/v0_9_1/json/server_capabilities.json');
const clientCapabilities = read('specification/v0_9_1/json/client_capabilities.json');
const basicCatalog = read('specification/v0_9_1/catalogs/basic/catalog.json');

const body = [
  `// GENERATED by scripts/embed-spec.mjs from a2ui-spec/. Do not edit.`,
  `/** The upstream commit the pinned spec was copied from. */`,
  `export const A2UI_SPEC_COMMIT = ${JSON.stringify(upstream.commit)};`,
  `/** A2UI v0.9.1 \`server_to_client.json\`, verbatim. */`,
  `export const SERVER_TO_CLIENT_SCHEMA: Record<string, unknown> = ${JSON.stringify(serverToClient)};`,
  `/** A2UI v0.9.1 \`common_types.json\`, verbatim. */`,
  `export const COMMON_TYPES_SCHEMA: Record<string, unknown> = ${JSON.stringify(commonTypes)};`,
  `/** A2UI v0.9.1 \`server_capabilities.json\`, verbatim: what an agent's card declares under the A2UI extension's params. */`,
  `export const SERVER_CAPABILITIES_SCHEMA: Record<string, unknown> = ${JSON.stringify(serverCapabilities)};`,
  `/** A2UI v0.9.1 \`client_capabilities.json\`, verbatim: what a client attaches as \`a2uiClientCapabilities\`. */`,
  `export const CLIENT_CAPABILITIES_SCHEMA: Record<string, unknown> = ${JSON.stringify(clientCapabilities)};`,
  `/** The id of the standard basic catalog, as its pinned \`catalog.json\` declares it. */`,
  `export const BASIC_CATALOG_ID = ${JSON.stringify(basicCatalog.catalogId)};`,
  `/** The standard basic catalog's \`catalog.json\`, verbatim: the options its components declare (the credential bar). */`,
  `export const BASIC_CATALOG_SCHEMA: Record<string, unknown> = ${JSON.stringify(basicCatalog)};`,
  '',
].join('\n');

mkdirSync(dirname(target), {recursive: true});
writeFileSync(target, body);
