/**
 * The composition doc (`../docs/composition.md`) is authored as markdown and shipped as a string
 * the prompt builder bundles — the sdk runs in the browser too, so it cannot read files. This
 * script embeds it into `src/prompt/composition.doc.generated.ts`; build, typecheck and test run
 * it first. Generated, never edited.
 */
import {mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const source = resolve(here, '../../docs/composition.md');
const target = resolve(here, '../src/prompt/composition.doc.generated.ts');

const markdown = readFileSync(source, 'utf8');
const header = `// GENERATED by scripts/embed-docs.mjs from docs/composition.md. Do not edit.\n`;
const body = `export const COMPOSITION_DOC = ${JSON.stringify(markdown)};\n`;

mkdirSync(dirname(target), {recursive: true});
writeFileSync(target, header + body);
