/**
 * The bundle's one CSS setup (SPEC §9.2): Radix Themes' stylesheet with every `:root`
 * selector rewritten onto the Provider's wrapper, so nothing the shell catalog brings
 * onto the page lands outside its own boundary — the client's collision detector
 * checks exactly that. Written into `src/` (vitest, vite) and `dist/` (consumers);
 * both copies are generated, never edited.
 */
import {createRequire} from 'node:module';
import {mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const WRAPPER = '.a2uiverse-shell-catalog';
const here = dirname(fileURLToPath(import.meta.url));
// The client's collision detector discovers a package's stylesheets by scanning its JS for
// `.css` string literals (regex-level, by design); the stock sheet must not be found through this
// script, only its scoped copy, so the specifier is assembled rather than written out.
const SOURCE_SHEET = ['@radix-ui/themes/styles', 'css'].join('.');
const source = createRequire(import.meta.url).resolve(SOURCE_SHEET);
const css = readFileSync(source, 'utf8');

const scoped = css.replace(/:root(?![\w-])/g, WRAPPER);
if (/:root/.test(scoped)) throw new Error('scope-radix: a :root selector survived the rewrite');
if (/(^|[,{}\s])(html|body)\s*[,{]/.test(scoped))
  throw new Error('scope-radix: the sheet carries an html/body selector');

// Custom properties the sheet reads but never declares are the ones Radix sets on elements at
// runtime (layout props such as --width, popper measurements such as
// --radix-select-trigger-width). Undeclared, a read would inherit whatever a neighbour set;
// declared `initial` on the wrapper it evaluates exactly as undeclared — guaranteed-invalid,
// so the fallback or the initial value applies — while an element's own inline value still
// wins. The boundary resets them instead of borrowing them.
const declared = new Set([...scoped.matchAll(/(--[\w-]+)\s*:/g)].map(m => m[1]));
const read = new Set([...scoped.matchAll(/var\(\s*(--[\w-]+)/g)].map(m => m[1]));
const runtimeSet = [...read].filter(name => !declared.has(name)).sort();
const reset = `${WRAPPER}{${runtimeSet.map(name => `${name}:initial;`).join('')}}\n`;

const header = `/* GENERATED by scripts/scope-radix.mjs from @radix-ui/themes/styles.css — every root-level selector rewritten onto ${WRAPPER}. Do not edit. */\n`;
for (const dir of ['src', 'dist']) {
  mkdirSync(resolve(here, '..', dir), {recursive: true});
  writeFileSync(resolve(here, '..', dir, 'radix-themes.scoped.css'), header + reset + scoped);
}
